site_name: Ro-DOU - ferramenta de clipping dos diários oficiais

nav:
  - Página Inicial: index.md
  - O que é Ro-DOU?: definicao/rodou.md
  - Como utilizar:
    - Introdução: como_utilizar/intro_utilizacao.md
    - Instalação e configuração: como_utilizar/instalacao.md
    - Usuários internos e externos: como_utilizar/usuarios.md
    - Notificação de erros: como_utilizar/notificacao_de_erros.md
  - Como funciona:
    - Introdução: como_funciona/intro_funcionamento.md
    - Compreendendo a pesquisa no D.O.U.: como_funciona/pesquisa_dou.md
    - Recursos e funcionalidades: como_funciona/recursos_funcionalidades.md
    - Parâmetros de pesquisa: como_funciona/parametros.md
    - Operadores de pesquisa avançada: como_funciona/operadores.md
    - Exemplos: como_funciona/exemplos.md
  - Como contribuir:
    - Contribuições: como_contribuir/contribuicoes.md
  - Oficinas e mídias:
    - Conteúdos sobre o Ro-DOU: oficinas_midias/oficinas_midias.md
  - Outros:
    - FAQ: outros/faq.md
    - Links relevantes: outros/links.md
    - Contato: outros/contato.md
  - CHANGELOG:
    - Changelog: changelog/changelog.md

theme:
  name: 'readthedocs'
